linters:
  presets:
    - bugs
    - comment
    - format
    - import
    - module
    - unused
  disable:
    # Produces ordering contradictory to VS Code's auto formatting.
    - gci
    # We don't have any denylisted dependencies
    - depguard