linters:
  presets:
    - bugs
    - comment
    - format
    - import
    - metalinter
    - module
    - performance
    - test
    - unused
  disable:
    # Produces ordering contradictory to VS Code's auto formatting.
    - gci
    # We don't have any denylisted dependencies
    - depguard
    # Don't require preallocating slices
    - prealloc
    # Don't require tests to be in separate package
    - testpackage
    # Permit tests to specify structs with default fields
    - exhaustruct