name: Create Pull Request for Branch

on:
  # Push to non-master branch
  push:
    branches-ignore: master

jobs:
  pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label: automatic
          draft: true
