name: Create Pull Request

on:
  # Push to non-master branch
  push:
    branches-ignore: master

jobs:
  create-pull-request:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          # Enable action-pull-request to diff branches
          fetch-depth: 0
      - uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          label: automatic
          draft: true
