name: Release Beta

on:
  # New release tagged.
  push:
    tags:
      - 'v[0-9]+.[0-9]+.*'
  # Manual trigger.
  workflow_dispatch:

jobs:
  release-beta:
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      # This is broad, but unfortunately it is required for creating
      # releases.
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: bazelbuild/setup-bazelisk@v3
      - name: Check Manifest
        run: |
          MANIFEST_VERSION=$(cat manifest-beta.json | python3 -c "import sys, json; print(json.load(sys.stdin)['version'])")
          TAG_VERSION=${{ github.ref_name }}
          test "v${MANIFEST_VERSION}" = "${TAG_VERSION}"
      - run: bazel build ...
      - run: bazel test --test_output=errors ...
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          fail_on_unmatched_files: true
          # bazel-bin symlink may not exist
          files: |
            bazel-out/k8-fastbuild/bin/chrome-ssh-agent-beta.zip
            bazel-out/k8-fastbuild/bin/chrome-ssh-agent.zip
      - name: Publish to Webstore
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: bazel-out/k8-fastbuild/bin/chrome-ssh-agent-beta.zip
          extension-id: onabphcdiffmanfdhkihllckikaljmhh
          client-id: ${{ secrets.WEBSTORE_CLIENT_ID }}
          client-secret: ${{ secrets.WEBSTORE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.WEBSTORE_REFRESH_TOKEN }}
